### ISSUE TITLE
Search and Regex buttons are white on white on IOS

### ISSUE THREAD

**Issue by gahr** [ursetto/chickadee#5]
Here's a screenshot of http://api.call-cc.org/5/doc/chickadee from iOS. Happens both with safari and firefox

![image](https://github.com/ursetto/chickadee/assets/959474/36cec603-8691-44dc-98f3-951dc66715a1)

**Comment by ursetto** [comment]
This should be fixed on the site now. Let me know and I'll cut a new egg release as well.

**Comment by gahr** [comment]
It is, thanks!
